### PR TITLE
Fixed smart contract based on feedback received in SnT

### LINKED ISSUE #29: Change smart contract based on SnT feedback
- [x] Endorsement policies? Who does the pdc go to?

- [x] Change output for verify to make it more useful - perhaps a boolean?

- [ ] MSPID - let the user know where this is used. Perhaps make it optional so they don't HAVE to provide an MSPId

- [x] Change name of collection file?

- [x] Change name of variable for PDC

- [x] Does the PDC name really need to be an argument if every peer in the network already knows the name of the collection?

### PR DESCRIPTION
**Pull request by au-shah**
Closes #29 
Signed-off-by: Akshat Shah <akshatshah@akshats-mbp.hursley.uk.ibm.com>

### CODE REVIEW

File: sampleContract/src/my-private-asset-contract.ts [hunk 1]
```diff
@@ -71,23 +71,23 @@ export class MyPrivateAssetContract extends Contract {
...
         }
 
         const actualHash: string = pdHashBytes.toString('hex');
 
         if (hashToVerify === actualHash) {
-            return '\nCalculated Hash provided: \n' + hashToVerify + '\n\n             MATCHES  <----->  \n\nHash from Private Data Hash State \n' + actualHash;
+            return true;
         } else {
-            throw new Error('Could not match the Private Data Hash State');
+            throw new Error('Could not match the Private Data Hash State. Please try again.');
```
Comment (erin-hughes) [inline sampleContract/src/my-private-asset-contract.ts]: Can we change this error message to "No match found for ${provided-hash}" or something like that? (you'll have to update your tests too)
